#!/usr/bin/env node

// Renders docs/catalog.md from the manifests.
//
// Hand-written catalog listings drift the moment a module is added — the prose in
// docs/ has done exactly that. This makes the listing a build artifact instead, and
// `npm test` fails when it is stale.

const fs = require("node:fs");
const path = require("node:path");
const {
  listModules,
  listPolicies,
  listProfiles,
  listRuntimes
} = require("./lib/composition-catalog");

const GENERATED_NOTICE = "<!-- Generated by scripts/generate-catalog.js. Do not edit; run `npm run docs:catalog`. -->";

function escapeCell(value) {
  return String(value || "").replace(/\|/g, "\\|").replace(/\s*\n\s*/g, " ").trim();
}

function table(headers, rows) {
  if (rows.length === 0) {
    return "_None._\n";
  }
  return [
    `| ${headers.join(" | ")} |`,
    `| ${headers.map(() => "---").join(" | ")} |`,
    ...rows.map((row) => `| ${row.map(escapeCell).join(" | ")} |`)
  ].join("\n") + "\n";
}

function formatList(values) {
  return values && values.length > 0 ? values.map((value) => `\`${value}\``).join(", ") : "—";
}

function buildCatalog(repoRoot) {
  const profiles = listProfiles(repoRoot);
  const runtimes = listRuntimes(repoRoot);
  const modules = listModules(repoRoot, {});
  const policies = listPolicies(repoRoot);

  const sections = [
    "# Catalog",
    "",
    GENERATED_NOTICE,
    "",
    "Every profile, runtime, module and policy currently in the catalog. This file is",
    "generated from the manifests — if it disagrees with them, it is stale, not wrong.",
    "",
    "For a filtered view, ask the CLI instead:",
    "",
    "```bash",
    "node scripts/init-repo.js list-modules --runtime rust",
    "node scripts/init-repo.js explain-stack --profile <name>",
    "```",
    "",
    "## Profiles",
    "",
    table(
      ["Profile", "Runtime(s)", "Default modules", "Description"],
      profiles.map((entry) => [
        `\`${entry.name}\``,
        formatList(entry.runtimes || (entry.recommendedRuntime ? [entry.recommendedRuntime] : [])),
        formatList(entry.defaultModules),
        entry.description
      ])
    ),
    "## Runtimes",
    "",
    table(
      ["Runtime", "Language", "Package manager(s)", "Description"],
      runtimes.map((entry) => [
        `\`${entry.name}\``,
        entry.language,
        formatList(entry.packageManagers),
        entry.description
      ])
    ),
    "## Modules",
    "",
    table(
      ["Module", "Category", "Runtimes", "Requires", "Conflicts with", "Description"],
      modules
        .slice()
        .sort((left, right) =>
          left.category.localeCompare(right.category) || left.name.localeCompare(right.name)
        )
        .map((entry) => [
          `\`${entry.name}\``,
          entry.category,
          formatList(entry.compatibleRuntimes),
          formatList(entry.requiresModules),
          formatList(entry.conflictsWith),
          entry.description
        ])
    ),
    "## Policies",
    "",
    table(
      ["Policy", "Description"],
      policies.map((entry) => [`\`${entry.name}\``, entry.description])
    )
  ];

  return sections.join("\n");
}

function catalogPath(repoRoot) {
  return path.join(repoRoot, "docs", "catalog.md");
}

function run() {
  const repoRoot = path.resolve(__dirname, "..");
  fs.writeFileSync(catalogPath(repoRoot), buildCatalog(repoRoot), "utf8");
  console.log(`Wrote ${path.relative(repoRoot, catalogPath(repoRoot))}`);
}

if (require.main === module) {
  run();
}

module.exports = {
  buildCatalog,
  catalogPath,
  run
};
